### ISSUE TITLE
build failing due to shell

### ISSUE THREAD

**Issue by vxtra1973** [Rudd-O/rattlesnakeos-build#5]
Hi,

I followed the instructions for setting up a jenkins build but it failed pretty early in getstack.

getstack runs using /bin/sh which and it seems to ignore the jenkins shell setting.

Looking at the last commits on this project, I'm wondering if it's just out of step with upstream?

I currently use rattlesnakeos but am looking to move away from the aws set up.

Vik

**Comment by vxtra1973** [comment]
The issue seems here:
https://github.com/Rudd-O/shared-jenkins-libraries/blob/c520a539ba7b70303a97843a9e9ed54316d03cae/vars/updateBuildNumberDisplayName.groovy

The script runs using /bin/sh but popd etc are bash functions

**Comment by vxtra1973** [comment]
moving this issue to https://github.com/Rudd-O/shared-jenkins-libraries

**Comment by Rudd-O** [comment]
I'm archiving this repository, sadly, because I use GrapheneOS now.
